/* ============================================================
   posts.js — Blog post data (ES / EN)
   ============================================================ */

const POSTS = [
  /* ── Medium posts (published, with links) ─────────────────── */
  {
    id: 'antipatrones-microservicios',
    titleEs: 'Antipatrones en Microservicios',
    titleEn: 'Microservices Anti-patterns',
    tags: ['Microservices'],
    date: '2023',
    href: 'https://felipepabon.medium.com/antipatrones-microservicios-1a7bf040633c',
    external: true,
  },
  {
    id: 'clean-arch-golang',
    titleEs: 'Estructura de carpetas para un API en Golang con Clean Architecture',
    titleEn: 'Folder Structure for a Golang API using Clean Architecture',
    tags: ['Clean Architecture', 'Golang', 'API Design'],
    date: '2023',
    href: 'https://felipepabon.medium.com/estructura-de-carpetas-para-un-api-en-golang-usando-arquitectura-limpia-o-clean-architecture-7d3918f4aec3',
    external: true,
  },
  {
    id: 'unit-testing-tdd',
    titleEs: 'Cómo definir buenas pruebas unitarias (TDD)',
    titleEn: 'How to Write Good Unit Tests (TDD)',
    tags: ['TDD', 'Testing'],
    date: '2023',
    href: 'https://felipepabon.medium.com/c%C3%B3mo-definir-buenas-pruebas-unitarias-tdd-3836fa614ec6',
    external: true,
  },

  /* ── Site articles ────────────────────────────────────────── */
  {
    id: 'ddd-strategic-overview',
    titleEs: 'DDD Estratégico: Un Overview',
    titleEn: 'Strategic DDD: An Overview',
    tags: ['DDD'],
    date: 'May 2026',
    href: 'ddd-strategic-overview.html', // path relative to /blog/
    external: false,
    published: true,
  },

  {
    id: 'atam-ejemplo-api-bancaria',
    titleEs: 'ATAM en Práctica: API de Movimientos Bancarios',
    titleEn: 'ATAM in Practice: A Banking Movements API',
    tags: ['Architecture', 'Design'],
    date: 'May 2026',
    href: 'atam-ejemplo-api-bancaria.html',
    external: false,
    published: true,
  },

  {
    id: 'sei-architecture-methods',
    titleEs: 'Métodos de Arquitectura del SEI: Un Overview',
    titleEn: 'SEI Software Architecture Methods: An Overview',
    tags: ['Architecture', 'Design'],
    date: 'May 2026',
    href: 'sei-architecture-methods.html',
    external: false,
    published: true,
  },

  /* ── Previous site posts (coming soon) ────────────────────── */
  {
    id: 'ddd-intro',
    titleEs: '¿Qué es DDD (Domain Driven Design)?',
    titleEn: 'What is DDD (Domain Driven Design)?',
    tags: ['DDD'],
    date: '2022',
    href: null,
    external: false,
  },
  {
    id: 'ddd-context-map',
    titleEs: '¿Qué es un Context Map (DDD)?',
    titleEn: 'What is a Context Map (DDD)?',
    tags: ['DDD'],
    date: '2022',
    href: null,
    external: false,
  },
  {
    id: 'ddd-tactical-strategic',
    titleEs: 'DDD Táctico y DDD Estratégico',
    titleEn: 'Tactical DDD and Strategic DDD',
    tags: ['DDD'],
    date: '2022',
    href: null,
    external: false,
  },
  {
    id: 'api-granularity',
    titleEs: '¿Cuál es el tamaño correcto de un API? Granularidad',
    titleEn: 'What is the Right API Size? Granularity',
    tags: ['API Design'],
    date: '2022',
    href: null,
    external: false,
  },
  {
    id: 'soa-intro',
    titleEs: '¿Qué es SOA? Una analogía orientada al servicio',
    titleEn: 'What is SOA? A Service-Oriented Analogy',
    tags: ['SOA', 'Architecture'],
    date: '2022',
    href: null,
    external: false,
  },
  {
    id: 'soa-governance',
    titleEs: '¿Qué es Gobierno SOA?',
    titleEn: 'What is SOA Governance?',
    tags: ['SOA'],
    date: '2022',
    href: null,
    external: false,
  },
  {
    id: 'soa-classification',
    titleEs: 'Clasificación de servicios en SOA',
    titleEn: 'Service Classification in SOA',
    tags: ['SOA'],
    date: '2022',
    href: null,
    external: false,
  },
  {
    id: 'reusable-components',
    titleEs: 'Variabilidad de componentes reutilizables',
    titleEn: 'Reusable Component Variability',
    tags: ['Architecture', 'Design'],
    date: '2022',
    href: null,
    external: false,
  },
  {
    id: 'spring-annotations',
    titleEs: 'Guía de anotaciones Spring Framework',
    titleEn: 'Spring Framework Annotations Guide',
    tags: ['Spring', 'Java'],
    date: '2022',
    href: null,
    external: false,
  },
  {
    id: 'azure-app-config',
    titleEs: 'Gestión de parámetros en .NET + Azure App Configuration',
    titleEn: 'Parameter Management in .NET + Azure App Configuration',
    tags: ['Azure', '.NET'],
    date: '2022',
    href: null,
    external: false,
  },
];
